version: '3.8'

services:
  # LocalAI service - OpenAI-compatible AI backend
  localai:
    image: localai/localai:latest
    container_name: localai
    ports:
      - "8080:8080"  # LocalAI API port
    environment:
      - THREADS=4
      - CONTEXT_SIZE=4096
      - MODELS_PATH=/models
      - DEBUG=true
      - CORS=true
    volumes:
      - localai-models:/models
      - ./localai-config:/config  # Optional: for model configurations
    restart: unless-stopped
    networks:
      - localai-network

volumes:
  localai-models:
    driver: local

networks:
  localai-network:
    driver: bridge